apiVersion: v1
kind: Pod
metadata:
  name: goat-home-secure-test
  namespace: security-lab
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: goat-home
    image: madhuakula/k8s-goat-home
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
