apiVersion: v1
kind: Pod
metadata:
  name: internal-proxy-secure-test
  namespace: security-lab
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: internal-api
    image: madhuakula/k8s-goat-internal-api
    ports:
    - containerPort: 3000
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
  - name: info-app
    image: madhuakula/k8s-goat-info-app
    ports:
    - containerPort: 5000
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
