apiVersion: v1
kind: Pod
metadata:
  name: poor-registry-secure-test
  namespace: security-lab
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: poor-registry
    image: madhuakula/k8s-goat-poor-registry
    ports:
    - containerPort: 5000
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
    volumeMounts:
    - name: registry-data
      mountPath: /var/custom/registry
  volumes:
  - name: registry-data
    emptyDir: {}
