apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-app-default-deny
  namespace: security-lab
spec:
  podSelector:
    matchLabels:
      app: secure-app
  policyTypes:
    - Ingress
    - Egress