{
    "spec":  {
                 "podSelector":  {
                                     "matchLabels":  {
                                                         "variant":  "variant-secure-9"
                                                     }
                                 },
                 "policyTypes":  [
                                     "Ingress",
                                     "Egress"
                                 ]
             },
    "metadata":  {
                     "namespace":  "ml-variants",
                     "name":  "variant-secure-9-deny"
                 },
    "apiVersion":  "networking.k8s.io/v1",
    "kind":  "NetworkPolicy"
}
